# https://docs.github.com/en/actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  XDEBUG_MODE: "coverage"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PHP with XDebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: xdebug, ctype, curl, json, libxml, mbstring, phar, xml, xmlwriter
        coverage: xdebug
        tools: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run static analysis of phpstan
      run: composer run-script phpstan

    - name: Run static analysis of codesniffer
      run: composer run-script cs

    - name: Run dependency check
      run: composer run-script deps

    - name: Run test suite
      run: composer run-script test
